### ISSUE TITLE
Support for NC24 and PHP8.1

### ISSUE THREAD

**Issue by nursoda** [nextcloud/twofactor_admin#229]
On my NC24b3 instance running on Arch linux with PHP 8.1, upon `occ app:enable twofactor_admin` and despite of adding `twofactor_admin` to the `app_install_overwrite` array in `config/config.php` I cannot enable the app since this requirement cannot(?) be overruled:
```
cannot be installed because the following dependencies are not fulfilled:
PHP with a version lower than 8.0 is required.
```
This is due to [appinfo/info.xml](https://github.com/ChristophWurst/twofactor_admin/blob/master/appinfo/info.xml) reading
```
<php min-version="7.2" max-version="8.0"/>
<nextcloud min-version="17" max-version="23"/>
```
Please change [appinfo/info.xml](https://github.com/ChristophWurst/twofactor_admin/blob/master/appinfo/info.xml) to
```
<php min-version="7.3" max-version="8.1"/>
<nextcloud min-version="21" max-version="24"/>
```
according to the most recent [app upgrade guide](https://docs.nextcloud.com/server/latest/developer_manual/app_publishing_maintenance/app_upgrade_guide/upgrade_to_24.html).

I'm not doing a PR since I cannot check or tell whether anything else must be changed (although I don't expect it). Manually changing [appinfo/info.xml](https://github.com/ChristophWurst/twofactor_admin/blob/master/appinfo/info.xml) and enabling the app works fine for me with NC24 and PHP8.1.

**Comment by nunesgh** [comment]
Is there any update on this?

**Comment by nursoda** [comment]
> I don't want to be locked out of my system accidentally.

I agree that this app should be made compliant (in fact you may just override the incompatibility warning to do so). Plus, I don't think that this app may ensure that you don't get locked out since you must log in as admin to use it – and all admins should definitely have 2FA enabled. If you can log in as admin, there are other ways to re-enable users to log-in (such as creating a 2FA-exception group (in admin/security and temporarily adding those users to that group). So, this app is more a convenient way to give access to one user. Plus, if you have shell access, you may use occ to disable 2FA for that user.

**Comment by b-pfl** [comment]
Yes, @ChristophWurst it would be much appreciated to enable support for NC24 and PHP8.1

**Comment by ChristophWurst** [comment]
I don't have time to maintain this app at the moment.

**Comment by ynott** [comment]
Our Nextcloud license paying company is having trouble upgrading to NC24 because they are using this twofactor_admin.

Do I need to create a support ticket to the nextcloud Portal?

**Comment by ChristophWurst** [comment]
> Do I need to create a support ticket to the nextcloud Portal?

Yes please.

**Comment by ChristophWurst** [comment]
See https://github.com/nextcloud/twofactor_admin/pull/258
