### ISSUE TITLE
Nextcloud 25 Support

### ISSUE THREAD

**Issue by andyxheli** [nextcloud/twofactor_admin#247]

**Comment by aov-arnold** [comment]
@ChristophWurst Will there be NC24 and NC25 support in the near future or do you have still no time to maintain this app?

**Comment by sunjam** [comment]
Working when force enabled.

**Comment by rmbleeker** [comment]
@aov-arnold see https://github.com/ChristophWurst/twofactor_admin/issues/229#issuecomment-1182858035

**Comment by andyxheli** [comment]
Admin app brakes NC 25 when generating a code internal server error after admin generates a call and user logs in

**Comment by ChristophWurst** [comment]
See https://github.com/nextcloud/twofactor_admin/pull/258

**Comment by andyxheli** [comment]
Thank you so much @ChristophWurst  for all your hard work

**Comment by nursoda** [comment]
Thanks! ETA for the release?

**Comment by ChristophWurst** [comment]
When it's ready

**Comment by svde** [comment]
Changes made today work for me on 25.0.1. Thank you.
