### ISSUE TITLE
Support localization

### ISSUE THREAD

**Issue by p-bo** [nextcloud/twofactor_admin#249]
Hello,
Would it be possible to follow instructions on:
https://docs.nextcloud.com/server/latest/developer_manual/basics/front-end/l10n.html
...and make your app more accessible for non-English speakers please?

Thanks :-)

**Comment by rmbleeker** [comment]
@p-bo see https://github.com/ChristophWurst/twofactor_admin/issues/229#issuecomment-1182858035

**Comment by ChristophWurst** [comment]
Looking at https://github.com/nextcloud/twofactor_admin/tree/main/templates I would say the app is ready for localization. Someone just has to set up the Transifex integration.

**Comment by nickvergessen** [comment]
Done
