### ISSUE TITLE
Two-Factor Admin reported not compatible with update 28.0.1 (Application ver. 4.4.0)

### ISSUE THREAD

**Issue by Athar42** [nextcloud/twofactor_admin#319]
Please make a clear and concise description of what the bug is.

==> I got the update proposal to 28.0.1 and "Two-Factor Admin" is reported to be "not compatible" with this release.

## Steps to reproduce
1. Install and enable this module with NC 28.0.0
2. Get the update message to NC 28.0.1
3. See the error :D 

### Expected behaviour
As the application is compatible to the 28 release, this shouldn't be triggered, so the app should be compatible (maybe a bad variable set somewhere ?)

### Actual behaviour
App is reported incompatible.

### Screenshots
![image](https://github.com/nextcloud/twofactor_admin/assets/44590042/1121da7f-8424-4661-a028-07a9a5d318b0)

## Server
Please complete the following information.

- Notes app version: 4.4.0
- Nextcloud version: 28.0.0
- OS: Debian
- Web server: Apache
- PHP version: 8.3
- Database: MySQL

## Client
Please complete the following information.

- Browser (incl. version): Firefox 121
 - OS: Win 11

## Log files
Add relevant parts of your `nextcloud.log` and/or your browser's JavaScript console here.

None needed

**Comment by Athar42** [comment]
Little update : Did update to 28.0.1, apps are still enabled and still working.
So the issue there is that this app is not compatible with PHP8.3 while NC28 is.

**Comment by Athar42** [comment]
Just in case, this code change hasn't been released (don't know if this is a miss or usual).

As this "issue" is closed but not released, is it really (close I mean :D ) ?

**Comment by tcitworld** [comment]
Issues are closed when a fix is included in the main code base, not when it's released.
